### ISSUE TITLE
Error while trying to fetch switch data

### ISSUE THREAD

**Issue by llgoncalves** [kytos/ui#17] opened 2018-03-09 19:56 UTC
The Kytos UI notifies that it can not fetch switch data.

## Logging
```
WARNING [kytos.core.interface] (Thread-4010) Couldn't get port 4294967294 speed, sw 00:...:02, feats 0 
WARNING [kytos.core.interface] (Thread-4010) Couldn't get port 4294967294 speed, sw 00:...:01, feats 0```

**Comment by hdiogenes** [comment] 2018-10-09 19:52
Duplicate of #16.

**Closed by hdiogenes** 2018-10-09 19:52 UTC
Labels: duplicate
